class CreatePrescriptions < ActiveRecord::Migration[5.0]
  def change
    create_table :prescriptions do |t|
      t.string :pi01
      t.string :pi02
      t.string :pi03
      t.string :pi04
      t.string :pi05
      t.string :pi06
      t.string :pi07
      t.string :pi08
      t.string :pi09
      t.string :pi10
      t.string :pi11
      t.string :pi12
      t.string :pi13
      t.string :pi14
      t.string :pi15
      t.string :pi16
      t.string :pi17
      t.string :pi18
      t.string :pi19
      t.string :pi20
      t.string :pi21
      t.string :pi22
      t.string :pi23
      t.string :pi24
      t.string :pi25
      t.string :pt01
      t.string :pt02
      t.string :pt03
      t.string :pt04
      t.string :pt05
      t.string :pt06
      t.string :pt07
      t.string :pt08
      t.string :pt09
      t.string :pt10
      t.string :pt11
      t.string :pt12
      t.string :pt13
      t.string :pt14
      t.string :pt15
      t.string :pt16
      t.string :pt17
      t.string :pt18
      t.string :pt19
      t.string :pt20
      t.string :pt21
      t.string :pt22
      t.string :pt23
      t.string :pt24
      t.string :pt25
      t.integer :po01
      t.integer :po02
      t.integer :po03
      t.integer :po04
      t.integer :po05
      t.integer :po06
      t.integer :po07
      t.integer :po08
      t.integer :po09
      t.integer :po10
      t.integer :po11
      t.integer :po12
      t.integer :po13
      t.integer :po14
      t.integer :po15
      t.integer :po16
      t.integer :po17
      t.integer :po18
      t.integer :po19
      t.integer :po20
      t.integer :po21
      t.integer :po22
      t.integer :po23
      t.integer :po24
      t.integer :po25
      t.datetime :pty01
      t.datetime :pty02
      t.datetime :pty03
      t.datetime :pty04
      t.datetime :pty05
      t.datetime :pty06
      t.datetime :pty07
      t.datetime :pty08
      t.datetime :pty09
      t.datetime :pty10
      t.datetime :pty11
      t.datetime :pty12
      t.datetime :pty13
      t.datetime :pty14
      t.datetime :pty15
      t.datetime :pty16
      t.datetime :pty17
      t.datetime :pty18
      t.datetime :pty19
      t.datetime :pty20
      t.datetime :pty21
      t.datetime :pty22
      t.datetime :pty23
      t.datetime :pty24
      t.datetime :pty25
      t.datetime :ptj01
      t.datetime :ptj02
      t.datetime :ptj03
      t.datetime :ptj04
      t.datetime :ptj05
      t.datetime :ptj06
      t.datetime :ptj07
      t.datetime :ptj08
      t.datetime :ptj09
      t.datetime :ptj10
      t.datetime :ptj11
      t.datetime :ptj12
      t.datetime :ptj13
      t.datetime :ptj14
      t.datetime :ptj15
      t.datetime :ptj16
      t.datetime :ptj17
      t.datetime :ptj18
      t.datetime :ptj19
      t.datetime :ptj20
      t.datetime :ptj21
      t.datetime :ptj22
      t.datetime :ptj23
      t.datetime :ptj24
      t.datetime :ptj25

      t.timestamps
    end
  end
end
